#!/bin/bash
# Starts the MamoLinux OEM Environment.

export DESKTOP_SESSION='mamolinux-oem-env'
export BROWSER='sudo -H -u mamolinux firefox'

/usr/bin/xfwm4 &
/usr/bin/basicwallpaper /usr/share/backgrounds/mamolinux-default-wallpaper.jpeg &
sudo -E /usr/bin/calamares -D8 # This is intentionally *not* backgrounded.
# If it exits...
pkill -9 basicwallpaper
pkill -9 xfconfd
pkill -9 xfwm4
