- name: "Accessories"
  description: "Accessories"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - cheese
    - font-manager
    - galculator
    - gnome-calculator
    - gnome-characters
    - gnome-system-monitor
    - gpick
    - gucharmap
    - flameshot
    - liferea
    - mediainfo-gui
    - mcomix
    - nitrogen
    - nomacs
    - p7zip-full
    - pdfarranger
    - plank
    # - arcolinux-plank-themes-git
    - screenkey
    # - vim-plugins
    - variety
- name: "Conky"
  description: "Conky and conky collection"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    # - arcolinux-conky-collection-git
    # - arcolinux-pipemenus-git
    # - conky-lua-archers
    - conky
    - conky-all
    - conky-cli
    - conky-std
    - yad
- name: "Git"
  description: "Git applications"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    # - gitahead-bin
    - gitg
    - git-gui
    # - gitfiend
    # - gitkraken
- name: "Password Manager"
  description: "Password managers"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - bitwarden
    # - enpass-bin
    - keepassxc
    - lastpass-cli
- name: "Privacy"
  description: "Applications that ensure your privacy"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    # - tor-browser
    - tor
    - privoxy
- name: "Virtualbox for Linux kernel"
  description: "Installs virtualbox for linux kernel"
  critical: false
  hidden: false
  selected: false
  expanded: false
  packages:
    - virtualbox
    - virtualbox-dkms
    - linux-headers
- name: "Virtualbox for Linux-lts kernel"
  description: "Installs virtualbox for linux-lts kernel"
  critical: false
  hidden: false
  selected: false
  expanded: false
  packages:
    - virtualbox
    - virtualbox-dkms
    - linux-lts-headers
    - linux-lts
- name: "Vmware"
  description: "Installs vmware software"
  critical: false
  hidden: false
  selected: false
  expanded: false
  packages:
    - open-vm-tools
    # - vmware-workstation
    - vmware-manager
    # - vmware-keymaps
- name: "Zsh"
  description: "Zsh"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - zsh
    - zsh-autosuggestions
    # - zsh-completions
    - zsh-syntax-highlighting
    - zsh-theme-powerlevel9k
    # - arcolinux-zsh-git
    # - oh-my-zsh-git
    # - oh-my-zsh-powerline-theme-git
